sns:
  user-server: http://localhost:9080
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    enabled: true
    sampling:
      probability: 1.0
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

spring:
  application:
    name: post-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/postdb
    username: post-server
    password: password!
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
resilience4j.circuitbreaker:
  configs:
    default:
      timeoutDuration: 3s
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 10000

